version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
